Checkpoint PR
jshilmover/shilmovercis233 pull request #4
Opened 2023-02-14 18:15 UTC by jshilmover

2023-02-14 21:00 UTC, kblake reviewed
A file change tweak but other than that looks good! Please continue with rest of assignment specifications.

2023-02-14 21:00 UTC, kblake commented on crud-app/resources/views/products/view_product.blade.php
> +<!DOCTYPE html>
Change the name of this file to the canonical name of `show.blade.php`

2023-02-14 21:00 UTC, kblake commented on crud-app/app/Http/Controllers/ProductController.php
> +        return view('products/view_product', [
navigate to `show` instead of `view_product`

2023-02-15 21:04 UTC, jshilmover commented
Index page: 
![image](https://user-images.githubusercontent.com/106402845/219157995-9c1aec55-c66f-40a1-aebf-e68921c4bf1e.png)
![image](https://user-images.githubusercontent.com/106402845/219158117-1c2cfa57-5d19-4399-b910-43740568cffe.png)

Show page:
![image](https://user-images.githubusercontent.com/106402845/219159097-e2306371-eadc-42f8-a94f-e60f3b3da3fe.png)

Create page:
![image](https://user-images.githubusercontent.com/106402845/219160165-85ef608c-e9a5-4894-bc2e-2fc3b3d06a78.png)

Edit page:
![image](https://user-images.githubusercontent.com/106402845/219160316-e73324fd-a276-4553-871c-81b359679000.png)

Delete confirmation:
![image](https://user-images.githubusercontent.com/106402845/219160437-38650a1a-87c2-4c90-94de-00f26853fece.png)

2023-02-15 22:08 UTC, kblake requested changes
Feedback:

- Create and leverage a layout file for all your blade templates to use. 
- You are missing an edit page.
- Rename your form element names to match table field names

2023-02-15 22:08 UTC, kblake commented on crud-app/app/Http/Controllers/ProductController.php
> +        $product->description = $request->description;
TODO: Update your form fields to match property and table field names and then you don' have to assign each one separately.

2023-02-15 22:08 UTC, kblake commented on crud-app/app/Http/Controllers/ProductController.php
> +        $product->description = $request->description;
Same here as in the store action

2023-02-15 22:08 UTC, kblake commented on crud-app/app/Models/Product.php
> +                'itemNumber' => 'required|numeric',
rename fields to match table fields

2023-02-20 21:04 UTC, kblake approved these changes
+5 ec for factory usage
-11 for unresolved feedback

2023-02-20 21:04 UTC, merged